import Head from "next/head";
import Image from 'next/image';
import { SignIn } from "@clerk/nextjs";

export default function Home() {

  return (
    <>
      <Head>
        <title>Simple Login - Fuxam</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/img/fuxam-logo.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#FE6078] to-[#0E121D]">
        <Image src="/img/fuxam-wr.png" alt="Fuxam logo" width={200} height={200} className=" mb-8"/>
        <SignIn afterSignInUrl="/dashboard" />
      </main>
    </>
  );
}
